MODEL: C:\Users\burov\Documents\pochta\pochta\models\bge-m3
DATASET: "C:/Users/burov/Documents/pochta/pochta/data/Пишу тебе. Корпус для хакатона (2024).xlsx"
UMAP: 
  neighbors: 15
  dist: 0.0
  components: 50
  metric: "cosine"
  random_state: 42
HDBSCAN:
  min_cluster_size: 5
  min_samples: 3
  metric: 'euclidean'
  cluster_selection_method: 'eom'
  prediction_data: True
TQDM:
  keep_patterns:
      - "VERB NOUN"      
      - "VERB ADP NOUN"      
      - "ADJ NOUN"            
      - "PRON ADJ NOUN"      
      - "NOUN NOUN"         
      - "ADV VERB"           
      - "VERB ADV"          
      - "ADJ ADJ NOUN"      
      - "VERB PRON NOUN"   
      - "ADP NOUN NOUN"    
      - "VERB DET NOUN"    
      - "ADJ VERB"     
      - "NOUN VERB"   

